version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "backend"
    ports:
      - "5432:5432"
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "demo@demo.com"
      PGADMIN_DEFAULT_PASSWORD: "demo"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - database-network

networks:
  database-network:
    driver: bridge
